version: "3.9"

services:
  orchestrator:
    build:
      context: .
      dockerfile: ./orchestrator/Dockerfile
    container_name: orchestrator
    ports:
      - "9000:8000"
    depends_on:
      - content-agent
      - scheduler-agent
      - analytics-agent

  content-agent:
    build:
      context: .
      dockerfile: ./content_agent/Dockerfile
    container_name: content-agent

  scheduler-agent:
    build:
      context: .
      dockerfile: ./scheduler_agent/Dockerfile
    container_name: scheduler-agent

  analytics-agent:
    build:
      context: .
      dockerfile: ./analytics_agent/Dockerfile
    container_name: analytics-agent
